Первая итерация
AlexandrZlnov/Practicum_Go_SprintFive pull request #1
Opened 2024-07-10 16:46 UTC by AlexandrZlnov

2024-07-10 17:21 UTC, just-musha commented
@AlexandrZlnov смотрю на название ПРа и сразу скажу - на будущее - все правки, по всем итерациям ревью (есил они будут) должны быть в одном ПРе. Название ветки из примера сбивает с толку, конечно.

2024-07-10 17:36 UTC, just-musha requested changes
Привет! Хорошая работа. Нужно сделать 3 вещи: форматирование кода, поправить формулу для walking и проверки на 0 добавить там где они нужны. Жду правки!

2024-07-10 17:36 UTC, just-musha commented on main.go
> +	return t.distance() / t.Duration.Hours()
Перед делением нужна проверка на 0, как было в 4 спринте. И ниже по коду - давай тоже сразу добавим такую проверку, где она нужна

2024-07-10 17:36 UTC, just-musha commented on main.go
> +	TrainingType: r.TrainingType,
Отступы поехали. Надо запустить `go fmt`

2024-07-10 17:36 UTC, just-musha commented on main.go
> +		TrainingType: w.TrainingType,
И тут отступы

2024-07-10 17:36 UTC, just-musha commented on main.go
> +		TrainingType: w.TrainingType,
Рекомендую подключить в vscode авто форматирование кода при сохранении файла

2024-07-10 17:36 UTC, just-musha commented on main.go
> +		TrainingType: s.TrainingType,
Отступы

2024-07-10 17:36 UTC, just-musha commented on main.go
> +	return ((CaloriesWeightMultiplier * w.Weight + (math.Pow(w.meanSpeed(), 2)/(w.Height/CmInM))*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours)
Нужно проверить формулу, все ли приведения сделаны. Должно получиться `947.82`

2024-07-12 13:35 UTC, AlexandrZlnov commented on main.go
> +	return t.distance() / t.Duration.Hours()
Добавил проверку деления на 0 везде где это встречается.

2024-07-12 13:37 UTC, AlexandrZlnov commented on main.go
> +	TrainingType: r.TrainingType,
Не до конца понял про отступы. 
Включил в настройках автоформатирование кода при сохранении. Но VS Code оставляет теже отступы. Запуск go fmt main.go тоже сделал. У меня сейчас интервал табуляции 4 пробела, может быть его нужно уменьшить? 
Так же, к примеру, при переопределении любого метода делаю один пробел между именем поля и значение и VS Code при сохранении добавляет пробелов, так чтобы значения были в один столбец (<Speed: r.meanSpeed()> форматирует в такой вид <Speed:        r.meanSpeed()>).

2024-07-12 13:39 UTC, AlexandrZlnov commented on main.go
> +	return ((CaloriesWeightMultiplier * w.Weight + (math.Pow(w.meanSpeed(), 2)/(w.Height/CmInM))*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours)
Средняя скорость не была приведена к значению в м/с, формулу исправил и вышел на требуемое значение 947.82.

2024-07-12 18:09 UTC, just-musha commented
@AlexandrZlnov теперь все хорошо с отступами! Посмотри сам diff в последнем коммите - отступы исправлены:

![image](https://github.com/user-attachments/assets/6935c443-eb89-4485-9f5f-5abb29422670)

2024-07-12 18:11 UTC, just-musha approved these changes
Теперь отлично! Принято! Успехов дальше в обучении.

2024-07-12 18:11 UTC, just-musha commented on main.go
> +	if r.Duration.Hours() == 0 {
Тут не обязательно тк нет деления на эту переменную

2024-07-12 18:11 UTC, just-musha commented on main.go
> +	if w.Height == 0 {
:+1:

2025-01-27 11:54 UTC, merged